### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Romvnly-Gaming** [espidev/ebackup#23]
Hey, I really like your plugin eBackup! I was just about to switch from ServerRestorer before I realized it's lacking a restore function (I know I can do it manually but it's a pain)

**Comment by espidev** [comment]
Restoring backups on live servers is always going to be prone to issues since the server is possibly using files and can cause corruption if I overwrite these files if they are used. The reason I've not added restoring is because I want to guarantee that the plugin doesn't break server files in this way.

When restoring your backups, always do it when the server is off.

**Comment by Romvnly-Gaming** [comment]
Alright, is there any FTP command I can use to grab a backup from the ftp server and slap it on my Debian based operating system so I can make a script that stops the server and restores a specified backup?

**Comment by espidev** [comment]
To be honest I haven't used FTP in a long time so I don't remember how to use it haha (I am lazy and I just use SFTP all the time, you can use the `scp` command with that to transfer files)

**Comment by Romvnly-Gaming** [comment]
Alright, thanks!
